import type {Linter} from 'eslint';
import env from 'globals';
import babelParser from '@babel/eslint-parser';
import stylistic from '@stylistic/eslint-plugin';

export interface BaseConfigOptions {
    strict?: boolean;
}

// eslint-disable-next-line complexity
export function configureBase({strict = false}: BaseConfigOptions = {}): Linter.Config[] {
    return [
        {
            languageOptions: {
                parser: babelParser,
                ecmaVersion: 2024,
                globals: {
                    ...env.browser,
                    ...env.node,
                    ...env.es2024,
                    ...env.worker,
                    ...env.commonjs,
                    ...env.jest,
                },
                parserOptions: {
                    sourceType: 'module',
                    ecmaFeatures: {
                        jsx: true,
                    },
                    requireConfigFile: false,
                },
            },
            linterOptions: {
                reportUnusedDisableDirectives: 'warn',
            },
            plugins: {
                '@stylistic': stylistic,
            },
            rules: {
                'array-callback-return': ['error', {checkForEach: true, allowVoid: true}],
                'constructor-super': 'error',
                'for-direction': 'off',
                'getter-return': 'warn',
                'no-async-promise-executor': 'warn',
                'no-await-in-loop': 'off',
                'no-class-assign': 'warn',
                'no-compare-neg-zero': 'off',
                'no-cond-assign': 'off',
                'no-const-assign': 'error',
                'no-constant-binary-expression': 'warn',
                'no-constant-condition': 'warn',
                'no-constructor-return': 'error',
                'no-control-regex': 'off',
                'no-debugger': 'error',
                'no-dupe-args': 'error',
                'no-dupe-class-members': 'warn',
                'no-dupe-else-if': 'error',
                'no-dupe-keys': 'warn',
                'no-duplicate-case': 'error',
                'no-duplicate-imports': 'warn',
                'no-empty-character-class': 'error',
                'no-empty-pattern': 'error',
                'no-ex-assign': 'error',
                'no-fallthrough': strict ? 'error' : 'warn',
                'no-func-assign': 'warn',
                'no-import-assign': 'error',
                'no-inner-declarations': strict ? 'error' : 'warn',
                'no-invalid-regexp': 'error',
                'no-irregular-whitespace': 'warn',
                'no-loss-of-precision': 'off',
                'no-misleading-character-class': 'error',
                'no-new-native-nonconstructor': 'error',
                'no-obj-calls': 'error',
                'no-promise-executor-return': 'error',
                'no-prototype-builtins': 'off',
                'no-self-assign': 'error',
                'no-self-compare': 'error',
                'no-setter-return': 'error',
                'no-sparse-arrays': strict ? 'error' : 'warn',
                'no-template-curly-in-string': 'off',
                'no-this-before-super': 'error',
                'no-unassigned-vars': 'error',
                'no-undef': 'error',
                'no-unexpected-multiline': 'error',
                'no-unmodified-loop-condition': 'warn',
                'no-unreachable': 'error',
                'no-unreachable-loop': 'error',
                'no-unsafe-finally': 'error',
                'no-unsafe-negation': 'error',
                'no-unsafe-optional-chaining': 'error',
                'no-unused-private-class-members': 'error',
                'no-unused-vars': [
                    'warn',
                    {
                        vars: 'local',
                        args: 'none',
                    },
                ],
                'no-use-before-define': ['error', {variables: false, classes: false, functions: true}],
                'no-useless-assignment': 'error',
                'no-useless-backreference': 'warn',
                'require-atomic-updates': 'warn',
                'use-isnan': 'error',
                'valid-typeof': 'error',

                'accessor-pairs': 'off',
                'arrow-body-style': 'off',
                'block-scoped-var': strict ? 'warn' : 'off',
                camelcase: 'error',
                'capitalized-comments': 'off',
                'class-methods-use-this': 'off',
                complexity: strict ? ['warn', 10] : 'off',
                'consistent-return': strict ? ['error', {treatUndefinedAsUnspecified: true}] : 'off',
                'consistent-this': 'off',
                curly: [
                    'error',
                    'all',
                ],
                'default-case': 'off',
                'default-case-last': 'error',
                'default-param-last': 'off',
                'dot-notation': [
                    'error',
                    {
                        allowKeywords: true,
                        allowPattern: '^catch$',
                    },
                ],
                eqeqeq: [
                    'error',
                    'allow-null',
                ],
                'func-name-matching': 'off',
                'func-names': strict ? ['warn', 'always'] : 'off',
                'func-style': 'off',
                'grouped-accessor-pairs': 'off',
                'guard-for-in': 'warn',
                'id-denylist': 'off',
                'id-length': 'off',
                'id-match': 'off',
                'init-declarations': strict ? 'warn' : 'off',
                'logical-assignment-operators': 'off',
                'max-classes-per-file': 'off',
                'max-depth': [
                    'warn',
                    strict ? 3 : 6,
                ],
                'max-lines': strict ? ['warn', 800] : 'off',
                'max-lines-per-function': 'off',
                'max-nested-callbacks': [
                    'warn',
                    3,
                ],
                'max-params': [
                    'warn',
                    6,
                ],
                'max-statements': strict ? ['warn', 30, {ignoreTopLevelFunctions: true}] : 'off',
                'new-cap': 'error',
                'no-alert': strict ? 'warn' : 'off',
                'no-array-constructor': 'error',
                'no-bitwise': 'off',
                'no-caller': 'off',
                'no-case-declarations': 'off',
                'no-console': 'off',
                'no-continue': 'off',
                'no-delete-var': 'warn',
                'no-div-regex': 'off',
                'no-else-return': 'warn',
                'no-empty': 'off',
                'no-empty-function': 'off',
                'no-empty-static-block': 'off',
                'no-eq-null': 'off',
                'no-eval': 'warn',
                'no-extend-native': 'error',
                'no-extra-bind': 'warn',
                'no-extra-boolean-cast': 'warn',
                'no-extra-label': 'off',
                'no-global-assign': strict ? 'error' : 'off',
                'no-implicit-coercion': 'off',
                'no-implicit-globals': 'off',
                'no-implied-eval': 'warn',
                'no-inline-comments': 'off',
                'no-invalid-this': 'off',
                'no-iterator': 'error',
                'no-label-var': 'warn',
                'no-labels': [
                    'warn',
                    {
                        allowLoop: true,
                    },
                ],
                'no-lone-blocks': 'warn',
                'no-lonely-if': strict ? 'error' : 'off',
                'no-loop-func': 'warn',
                'no-magic-numbers': 'off',
                'no-multi-assign': 'off',
                'no-multi-str': 'warn',
                'no-negated-condition': strict ? 'warn' : 'off',
                'no-nested-ternary': 'off',
                'no-new': strict ? 'error' : 'off',
                'no-new-func': strict ? 'error' : 'off',
                'no-new-wrappers': 'error',
                'no-nonoctal-decimal-escape': 'off',
                'no-object-constructor': 'off',
                'no-octal': 'warn',
                'no-octal-escape': 'warn',
                'no-param-reassign': 'off',
                'no-plusplus': 'off',
                'no-proto': 'error',
                'no-redeclare': strict ? 'error' : 'warn',
                'no-regex-spaces': strict ? 'error' : 'off',
                'no-restricted-exports': 'off',
                'no-restricted-globals': 'off',
                'no-restricted-imports': 'off',
                'no-restricted-properties': 'off',
                'no-restricted-syntax': 'off',
                'no-return-assign': [strict ? 'error' : 'warn', 'except-parens'],
                'no-script-url': 'warn',
                'no-sequences': 'off',
                'no-shadow': 'off',
                'no-shadow-restricted-names': 'error',
                'no-ternary': 'off',
                'no-throw-literal': 'error',
                'no-undef-init': 'warn',
                'no-undefined': 'off',
                'no-underscore-dangle': 'warn',
                'no-unneeded-ternary': 'error',
                'no-unused-expressions': ['warn', {allowShortCircuit: true}],
                'no-unused-labels': 'error',
                'no-useless-call': 'warn',
                'no-useless-catch': 'warn',
                'no-useless-computed-key': 'error',
                'no-useless-concat': 'warn',
                'no-useless-constructor': strict ? 'error' : 'warn',
                'no-useless-escape': 'error',
                'no-useless-rename': 'error',
                'no-useless-return': strict ? 'error' : 'warn',
                'no-var': 'warn',
                'no-void': 'off',
                'no-warning-comments': 'off',
                'no-with': strict ? 'error' : 'warn',
                'object-shorthand': 'off',
                'one-var': ['error', 'never'],
                'operator-assignment': 'off',
                'prefer-arrow-callback': strict ? ['warn', {allowNamedFunctions: true}] : 'off',
                'prefer-const': 'off',
                'prefer-destructuring': 'off',
                'prefer-exponentiation-operator': 'off',
                'prefer-named-capture-group': 'off',
                'prefer-numeric-literals': strict ? 'error' : 'off',
                'prefer-object-has-own': 'off',
                'prefer-object-spread': 'off',
                'prefer-promise-reject-errors': 'error',
                'prefer-regex-literals': 'warn',
                'prefer-rest-params': 'error',
                'prefer-spread': strict ? 'warn' : 'off',
                'prefer-template': 'off',
                radix: 'error',
                'require-await': 'off',
                'require-unicode-regexp': 'off',
                'require-yield': 'off',
                'sort-imports': 'off',
                'sort-keys': 'off',
                'sort-vars': 'off',
                strict: 'off',
                'symbol-description': 'warn',
                'vars-on-top': 'off',
                yoda: 'warn',

                'unicode-bom': 'warn',

                '@stylistic/array-bracket-newline': ['warn', 'consistent'],
                '@stylistic/array-bracket-spacing': ['error', 'never'],
                '@stylistic/array-element-newline': ['warn', 'consistent'],
                '@stylistic/arrow-parens': ['error', 'as-needed'],
                '@stylistic/arrow-spacing': 'error',
                '@stylistic/block-spacing': ['error', 'never'],
                '@stylistic/brace-style': [
                    'warn',
                    'stroustrup',
                    {},
                ],
                '@stylistic/comma-dangle': [
                    'error',
                    {
                        arrays: 'always-multiline',
                        objects: 'always-multiline',
                        imports: 'always-multiline',
                        exports: 'always-multiline',
                        functions: 'never',
                    },
                ],
                '@stylistic/comma-spacing': [
                    'error',
                    {
                        before: false,
                        after: true,
                    },
                ],
                '@stylistic/comma-style': [
                    'error',
                    'last',
                ],
                '@stylistic/computed-property-spacing': [
                    'error',
                    'never',
                ],
                '@stylistic/curly-newline': ['error', {multiline: true, consistent: true}],
                '@stylistic/dot-location': ['error', 'property'],
                '@stylistic/eol-last': ['error'],
                '@stylistic/function-call-argument-newline': ['error', 'consistent'],
                '@stylistic/function-call-spacing': ['error', 'never'],
                '@stylistic/function-paren-newline': ['error', 'multiline'],
                '@stylistic/generator-star-spacing': [
                    'error',
                    {
                        before: false,
                        after: true,
                    },
                ],
                '@stylistic/implicit-arrow-linebreak': 'off',
                '@stylistic/indent': [
                    'error',
                    4,
                    {
                        SwitchCase: 1,
                    },
                ],
                '@stylistic/indent-binary-ops': 'off',
                '@stylistic/jsx-child-element-spacing': 'off',
                '@stylistic/jsx-closing-bracket-location': 'off',
                '@stylistic/jsx-closing-tag-location': 'off',
                '@stylistic/jsx-curly-brace-presence': 'off',
                '@stylistic/jsx-curly-newline': 'off',
                '@stylistic/jsx-curly-spacing': 'off',
                '@stylistic/jsx-equals-spacing': 'off',
                '@stylistic/jsx-first-prop-new-line': 'off',
                '@stylistic/jsx-function-call-newline': 'off',
                '@stylistic/jsx-indent': 'off',
                '@stylistic/jsx-indent-props': 'off',
                '@stylistic/jsx-max-props-per-line': 'off',
                '@stylistic/jsx-newline': 'off',
                '@stylistic/jsx-one-expression-per-line': 'off',
                '@stylistic/jsx-pascal-case': 'off',
                '@stylistic/jsx-props-no-multi-spaces': strict ? 'error' : 'off',
                '@stylistic/jsx-quotes': ['error', 'prefer-double'],
                '@stylistic/jsx-self-closing-comp': 'off',
                '@stylistic/jsx-sort-props': 'off',
                '@stylistic/jsx-tag-spacing': 'off',
                '@stylistic/jsx-wrap-multilines': 'off',
                '@stylistic/key-spacing': [
                    'error',
                    {
                        beforeColon: false,
                        afterColon: true,
                    },
                ],
                '@stylistic/keyword-spacing': 'error',
                '@stylistic/line-comment-position': 'off',
                '@stylistic/linebreak-style': 'off',
                '@stylistic/lines-around-comment': 'off',
                '@stylistic/lines-between-class-members': 'off',
                '@stylistic/max-len': [
                    'error',
                    120,
                    4,
                    {
                        ignoreUrls: true,
                        ignorePattern: 'data:image\\/',
                    },
                ],
                '@stylistic/max-statements-per-line': 'error',
                '@stylistic/member-delimiter-style': 'off',
                '@stylistic/multiline-comment-style': 'off',
                '@stylistic/multiline-ternary': 'off',
                '@stylistic/new-parens': 'warn',
                '@stylistic/newline-per-chained-call': 'off',
                '@stylistic/no-confusing-arrow': [
                    'error',
                    {
                        allowParens: true,
                    },
                ],
                '@stylistic/no-extra-parens': 'off',
                '@stylistic/no-extra-semi': 'error',
                '@stylistic/no-floating-decimal': strict ? 'error' : 'off',
                '@stylistic/no-mixed-operators': 'off',
                '@stylistic/no-mixed-spaces-and-tabs': 'error',
                '@stylistic/no-multi-spaces': [
                    'error',
                    {
                        exceptions: {
                            Property: true,
                            BinaryExpression: true,
                            VariableDeclarator: true,
                        },
                    },
                ],
                '@stylistic/no-multiple-empty-lines': strict ? 'warn' : 'off',
                '@stylistic/no-tabs': ['error'],
                '@stylistic/no-trailing-spaces': 'error',
                '@stylistic/no-whitespace-before-property': 'error',
                '@stylistic/nonblock-statement-body-position': 'off',
                '@stylistic/object-curly-newline': [
                    'error',
                    {multiline: true, consistent: true},
                ],
                '@stylistic/object-curly-spacing': ['error', 'never'],
                '@stylistic/object-property-newline': 'off',
                '@stylistic/one-var-declaration-per-line': ['error'],
                '@stylistic/operator-linebreak': ['error', 'before'],
                '@stylistic/padded-blocks': 'off',
                '@stylistic/padding-line-between-statements': 'off',
                '@stylistic/quote-props': ['warn', 'as-needed'],
                '@stylistic/quotes': [
                    'error',
                    'single',
                    {
                        avoidEscape: true,
                    },
                ],
                '@stylistic/rest-spread-spacing': ['error', 'never'],
                '@stylistic/semi': ['error', 'always'],
                '@stylistic/semi-spacing': 'error',
                '@stylistic/semi-style': ['error', 'last'],
                '@stylistic/space-before-blocks': ['error', 'always'],
                '@stylistic/space-before-function-paren': [
                    'error',
                    {
                        anonymous: 'always',
                        named: 'never',
                        asyncArrow: 'always',
                    },
                ],
                '@stylistic/space-in-parens': ['error', 'never'],
                '@stylistic/space-infix-ops': 'error',
                '@stylistic/space-unary-ops': 'warn',
                '@stylistic/spaced-comment': [
                    'error',
                    'always',
                    {
                        exceptions: [
                            '-',
                            '+',
                            '\'',
                            '#',
                        ],
                        block: {
                            balanced: true,
                        },
                    },
                ],
                '@stylistic/switch-colon-spacing': ['error', {before: false, after: true}],
                '@stylistic/template-curly-spacing': ['error', 'never'],
                '@stylistic/template-tag-spacing': ['error', 'never'],
                '@stylistic/type-annotation-spacing': 'error',
                '@stylistic/type-generic-spacing': 'error',
                '@stylistic/type-named-tuple-spacing': 'error',
                '@stylistic/wrap-iife': ['error', 'any'],
                '@stylistic/wrap-regex': 'off',
                '@stylistic/yield-star-spacing': 'off',
            },
        },
    ];
}
