import type {Linter} from 'eslint';
import {parser, plugin} from 'typescript-eslint';
import {configureBase} from './base.js';

export interface TypeScriptConfigOptions {
    strict?: boolean;
    typeCheck?: boolean;
}

// eslint-disable-next-line complexity
export function configureTypeScript(options: TypeScriptConfigOptions = {}): Linter.Config[] {
    const {strict = false, typeCheck = true} = options;
    const [base] = configureBase({strict});
    const files = ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.mtsx', '**/*.cts', '**/*.ctsx'];
    // 原则上`tsc`可以检测出来的规则均关闭
    return [
        {
            ...base,
            files,
        },
        {
            files,
            languageOptions: {
                // @ts-expect-error https://github.com/typescript-eslint/typescript-eslint/issues/10899
                parser: parser,
                parserOptions: {
                    projectService: typeCheck,
                },
            },
            plugins: {
                // @ts-expect-error https://github.com/typescript-eslint/typescript-eslint/issues/10899
                '@typescript-eslint': plugin,
            },
            rules: {
                '@typescript-eslint/adjacent-overload-signatures': 'error',
                '@typescript-eslint/array-type': [
                    'error',
                    {
                        default: 'array-simple',
                        readonly: 'array-simple',
                    },
                ],
                '@typescript-eslint/await-thenable': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/ban-ts-comment': strict
                    ? [
                        'warn',
                        {
                            'ts-expect-error': 'allow-with-description',
                            'ts-ignore': 'allow-with-description',
                            'ts-nocheck': 'allow-with-description',
                            'ts-check': 'allow-with-description',
                        },
                    ]
                    : 'off',
                '@typescript-eslint/ban-tslint-comment': 'off',
                '@typescript-eslint/class-literal-property-style': 'off',
                '@typescript-eslint/class-methods-use-this': 'off',
                '@typescript-eslint/consistent-generic-constructors': ['error', 'constructor'],
                '@typescript-eslint/consistent-indexed-object-style': 'off',
                '@typescript-eslint/consistent-return': 'off',
                '@typescript-eslint/consistent-type-assertions': 'error',
                '@typescript-eslint/consistent-type-definitions': [
                    'error',
                    'interface',
                ],
                '@typescript-eslint/consistent-type-exports': (typeCheck && strict) ? 'error' : 'off',
                '@typescript-eslint/consistent-type-imports': strict ? 'error' : 'off',
                '@typescript-eslint/default-param-last': 'off',
                '@typescript-eslint/dot-notation': typeCheck
                    ? [
                        'error',
                        {
                            allowIndexSignaturePropertyAccess: true,
                        },
                    ]
                    : 'off',
                '@typescript-eslint/explicit-function-return-type': 'off',
                '@typescript-eslint/explicit-member-accessibility': [
                    'error',
                    {
                        accessibility: 'no-public',
                    },
                ],
                '@typescript-eslint/explicit-module-boundary-types': 'off',
                '@typescript-eslint/init-declarations': [
                    'error',
                ],
                '@typescript-eslint/max-params': 'off',
                '@typescript-eslint/member-ordering': 'warn',
                '@typescript-eslint/method-signature-style': 'off',
                '@typescript-eslint/naming-convention': 'off',
                '@typescript-eslint/no-array-constructor': 'error',
                '@typescript-eslint/no-array-delete': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-base-to-string': 'off',
                '@typescript-eslint/no-confusing-non-null-assertion': 'off',
                '@typescript-eslint/no-confusing-void-expression': 'off',
                '@typescript-eslint/no-deprecated': 'off',
                '@typescript-eslint/no-dupe-class-members': 'error',
                '@typescript-eslint/no-duplicate-enum-values': 'off',
                '@typescript-eslint/no-duplicate-type-constituents': (typeCheck && strict) ? 'warn' : 'off',
                '@typescript-eslint/no-dynamic-delete': 'off',
                '@typescript-eslint/no-empty-function': 'off',
                '@typescript-eslint/no-empty-interface': 'warn',
                '@typescript-eslint/no-empty-object-type': 'warn',
                '@typescript-eslint/no-explicit-any': 'off',
                '@typescript-eslint/no-extra-non-null-assertion': 'error',
                '@typescript-eslint/no-extraneous-class': 'error',
                '@typescript-eslint/no-floating-promises': (typeCheck && strict)
                    ? ['error', {ignoreVoid: true}]
                    : 'off',
                '@typescript-eslint/no-for-in-array': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-implied-eval': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/no-import-type-side-effects': 'error',
                '@typescript-eslint/no-inferrable-types': 'off',
                '@typescript-eslint/no-invalid-this': 'off',
                '@typescript-eslint/no-invalid-void-type': 'off',
                '@typescript-eslint/no-loop-func': 'off',
                '@typescript-eslint/no-loss-of-precision': 'off',
                '@typescript-eslint/no-magic-numbers': 'off',
                '@typescript-eslint/no-meaningless-void-operator': 'off',
                '@typescript-eslint/no-misused-new': 'error',
                '@typescript-eslint/no-misused-promises': 'off',
                '@typescript-eslint/no-misused-spread': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-mixed-enums': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-namespace': 'error',
                '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
                '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
                '@typescript-eslint/no-non-null-assertion': 'error',
                '@typescript-eslint/no-redeclare': 'error',
                '@typescript-eslint/no-redundant-type-constituents': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/no-require-imports': 'error',
                '@typescript-eslint/no-restricted-imports': 'off',
                '@typescript-eslint/no-restricted-types': 'off',
                '@typescript-eslint/no-shadow': 'off',
                '@typescript-eslint/no-this-alias': 'error',
                '@typescript-eslint/no-type-alias': 'off',
                '@typescript-eslint/no-unnecessary-boolean-literal-compare': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unnecessary-condition': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'off',
                '@typescript-eslint/no-unnecessary-qualifier': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unnecessary-template-expression': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unnecessary-type-arguments': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/no-unnecessary-type-assertion': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unnecessary-type-constraint': 'error',
                '@typescript-eslint/no-unnecessary-type-conversion': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/no-unnecessary-type-parameters': 'off',
                '@typescript-eslint/no-unsafe-argument': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unsafe-assignment': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unsafe-call': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unsafe-declaration-merging': strict ? 'error' : 'off',
                '@typescript-eslint/no-unsafe-enum-comparison': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unsafe-function-type': 'off',
                '@typescript-eslint/no-unsafe-member-access': 'off',
                '@typescript-eslint/no-unsafe-return': (typeCheck && strict) ? 'error' : 'off',
                '@typescript-eslint/no-unsafe-type-assertion': 'off',
                '@typescript-eslint/no-unsafe-unary-minus': typeCheck ? 'error' : 'off',
                '@typescript-eslint/no-unused-expressions': 'off',
                '@typescript-eslint/no-unused-vars': [
                    'error',
                    {
                        vars: 'all',
                        args: 'after-used',
                        ignoreRestSiblings: true,
                    },
                ],
                '@typescript-eslint/no-use-before-define': 'error',
                '@typescript-eslint/no-useless-constructor': 'error',
                '@typescript-eslint/no-useless-empty-export': 'off',
                '@typescript-eslint/no-var-requires': 'error',
                '@typescript-eslint/no-wrapper-object-types': 'off',
                '@typescript-eslint/non-nullable-type-assertion-style': typeCheck ? 'error' : 'off',
                '@typescript-eslint/only-throw-error': typeCheck ? 'error' : 'off',
                '@typescript-eslint/parameter-properties': 'off',
                '@typescript-eslint/prefer-as-const': 'error',
                '@typescript-eslint/prefer-destructuring': 'off',
                '@typescript-eslint/prefer-enum-initializers': 'error',
                '@typescript-eslint/prefer-find': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-for-of': 'error',
                '@typescript-eslint/prefer-function-type': 'error',
                '@typescript-eslint/prefer-includes': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-literal-enum-member': 'off',
                '@typescript-eslint/prefer-namespace-keyword': 'error',
                '@typescript-eslint/prefer-nullish-coalescing': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-optional-chain': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-promise-reject-errors': typeCheck ? 'error' : 'off',
                '@typescript-eslint/prefer-readonly': typeCheck ? 'error' : 'off',
                '@typescript-eslint/prefer-readonly-parameter-types': 'off',
                '@typescript-eslint/prefer-reduce-type-parameter': 'off',
                '@typescript-eslint/prefer-regexp-exec': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-return-this-type': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-string-starts-ends-with': typeCheck ? 'warn' : 'off',
                '@typescript-eslint/prefer-ts-expect-error': 'error',
                '@typescript-eslint/promise-function-async': 'off',
                '@typescript-eslint/related-getter-setter-pairs': 'off',
                '@typescript-eslint/require-array-sort-compare': 'off',
                '@typescript-eslint/require-await': 'off',
                '@typescript-eslint/restrict-plus-operands': typeCheck ? 'error' : 'off',
                '@typescript-eslint/restrict-template-expressions': 'off',
                '@typescript-eslint/return-await': 'off',
                '@typescript-eslint/sort-type-constituents': 'off',
                '@typescript-eslint/strict-boolean-expressions': 'off',
                '@typescript-eslint/switch-exhaustiveness-check': typeCheck ? 'error' : 'off',
                '@typescript-eslint/triple-slash-reference': 'error',
                '@typescript-eslint/typedef': 'off',
                '@typescript-eslint/unbound-method': 'off',
                '@typescript-eslint/unified-signatures': 'warn',
                '@typescript-eslint/use-unknown-in-catch-callback-variable': typeCheck ? 'error' : 'off',
                '@typescript-eslint/indent': 'off',
                'no-empty-function': 'off',
                'no-extra-parens': 'off',
                '@typescript-eslint/no-extra-parens': 'off',
                '@typescript-eslint/no-parameter-properties': 'off',
                'no-unused-vars': 'off',
                'init-declarations': 'off',

                'constructor-super': 'off',
                'getter-return': 'off',
                'no-class-assign': 'off',
                'no-const-assign': 'off',
                'no-dupe-args': 'off',
                'no-dupe-class-members': 'off',
                'no-dupe-keys': 'off',
                'no-func-assign': 'off',
                'no-import-assign': 'off',
                'no-new-symbol': 'off',
                'no-obj-calls': 'off',
                'no-redeclare': 'off',
                'no-setter-return': 'off',
                'no-this-before-super': 'off',
                'no-undef': 'off',
                'no-unreachable': 'off',
                'no-unsafe-negation': 'off',
                'no-with': 'off',
                'no-duplicate-imports': 'off',
            },
        },
    ];
}
